Feature/login
sandra-n/hello-world pull request #7
Opened 2019-05-08 13:23 UTC by sandra-n

Receive as input: e-mail and password.
Verify if this user is in the database (comparing hash codes).
If it OK, sends a token (console.log)

2019-05-08 13:58 UTC, felipewaku commented on .gitignore
> +node_modules/
Além da `node_modules` é bom incluir a pasta `dist` no `.gitignore` porque ela só tem o código javascript compilado

2019-05-08 13:58 UTC, felipewaku commented on package.json
> +  },
Melhor colocar o `@types/express` e `typescript` nas `devDependencies` um pouco disso aqui: https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file

Mas resumindo em `dependencies` você coloca as dependências que vão ser utilizadas na lógica do código como bibliotecas para tratar request, json, token, banco de dados, etc, e nas `devDependencies` você coloca dependências que vão auxiliar no desenvolvimento como tipos do typescript  e o próprio typescript que é utilizado para compilar o código typescript para javascript.

2019-05-08 13:58 UTC, felipewaku commented on telalogin/login.ts
> +/*import readline = require('readline');
Não sei o quanto é cobrado no onboard, mas nos projetos é bom deixar o código sempre limpo então códigos comentados que você tirou só para testes é bom apagar antes de fazer o commit.

2019-05-08 13:58 UTC, felipewaku commented on telalogin/login.ts
> +var senha_dada: string;
Essas duas variáveis poderia ficar dentro da função no `app.post` porque da forma como estão elas poderiam ser acessadas por qualquer função desse arquivo e isso poderia causar problemas inesperados como um outro endpoint mudar o valor delas enquanto uma lógica está acontecendo.

2019-05-08 13:58 UTC, felipewaku commented on telalogin/queries.ts
> +    var hashuser = hash.digest('hex');
Geralmente não usamos mais `var` no typescript ou javascript porque ele tem alguns comportamentos inesperados na inicialização da variável. 

É melhor usar `let` ou `const`. Tentamos sempre usar `const` quando o valor não muda como na linha: `const app: express.Application = express();` e `let `quando o valor da variável mudar.

2019-05-08 13:58 UTC, felipewaku commented on telalogin/login.ts
> +    verificaUsuario(req, res);
É bom manter um padrão na nomeação de variáveis ou funções. Aqui você está usando snake case (separação usando underscore) nas variáveis `email_dado` e `senha_dada`  e camelCase (separar utilizando maiúsculas) no nome da função.
O padrão para typescript e javascript é usar `camelCase`, então melhor mudar para `emailDado` e `senhaDada`

2019-05-08 13:58 UTC, felipewaku commented on telalogin/login.ts
> +    console.log(req.body.senha);
Esses dois `console.log` estão redundantes com o de baixo, melhor deixar só um deles para ficar menos código

2019-05-08 13:58 UTC, felipewaku commented on telalogin/queries.ts
> +            console.log(geraToken(email));
A função `geraToken` pede um nome nos seus argumentos, mas aqui está sendo passado um e-mail. Para deixar o código mais condizente com o que está acontecendo é melhor mudar o geraToken para e-mail

2019-05-08 13:58 UTC, felipewaku commented on telalogin/queries.ts
> +            res.status(200).send(results.rows);
Não tenho certeza, mas não deveriamos mandar o token na resposta?

2019-05-08 13:58 UTC, felipewaku commented on telalogin/queries.ts
> +import { isNull, isNullOrUndefined } from 'util';
Essas duas funções não estão sendo utilizadas então poderia tirar elas do import

2019-05-08 13:58 UTC, felipewaku commented on telalogin/queries.ts
> +import jwt = require('jsonwebtoken');
Eita não sabia que isso funcionava 😬 

É melhor deixar todos os imports no padrão `import jwt frrom 'jsonwebtoken'`

2019-05-09 11:53 UTC, alanraso commented on telalogin/queries.ts
> +import jwt = require('jsonwebtoken');
Funciona, e o import automático faz bastante isso.

2019-05-09 11:56 UTC, alanraso commented on src/telalogin/checkuser.ts
> +        var hashUser = calculateHash(senha);
@sandra-n 
1. Como o Koji ressaltou, é melhor usarmos `const` aqui. E `let` para variáveis que mudarão depois.
2. O nome da variável não ilustra muito bem o valor que ela guarda, porque você está fazendo um hash de uma senha, não de um usuário, certo?

2019-05-09 12:06 UTC, alanraso approved these changes

2019-05-09 12:06 UTC, alanraso commented on src/telalogin/errors.ts
> +export function queryErrors (error: Error,results: QueryResult, res) : boolean{
Pra você já ir acostumando com nosso `lint` (que é uma ferramenta que analisa código e faz umas restrições), segue algumas coisas que adotamos pra que o código de todos fique mais padronizado:

1. Não precisa de espaço entre o nome da função e o `(`
2. Não precisa de espaço entre o `)` e o `:`
3. É legal ter um espaço entre o tipo do retorno e o `{`
4. Depois de fechar as condicionais dos ifs, colocamos um espaço tambem (depois do `)`)

2019-05-09 12:06 UTC, alanraso commented on src/telalogin/login.ts
> +    let senhaGiven: string;
Variável em português

2019-05-09 12:06 UTC, alanraso commented on src/telalogin/login.ts
> +    senhaGiven = req.body.senha;
Aqui você não precisa declarar a variável com `let` se ela será assinalada apenas uma vez. Pode colocar direto o valor nela:

```typescript
const emailGiven = req.body.email;
const passwordGiven = req.body.senha;
```

2019-05-09 12:06 UTC, alanraso commented on src/telalogin/token.ts
> +    const header = {
Esse header não está sendo usado né? Pode remover.

2019-05-09 12:06 UTC, alanraso commented on src/telalogin/token.ts
> +        "name": email
Essa chave desse objeto que você definiu não condiz com o valor (nome -> email)

2019-05-09 12:06 UTC, alanraso commented on src/telalogin/token.ts
> +    const secret = 'umafrasequalquerparateste';
Como esse `secret` será o mesmo para qualquer token gerado no seu server, você pode defini-lo fora da função. Assim você não fica criando essa variável sempre que um token for gerado. Concorda?

2019-05-09 12:11 UTC, alanraso requested changes
Algumas coisas legais de você fazer antes de mergear:
+ Remover os códigos que não estão mais sendo usados (vi que tem alguns antigos que você não usa mais)
+ Corrigir as identações e espaçamentos dos arquivos que vão ficar (e que devem ter sido mexidos antes do `.editorconfig` entrar)
+ Fazer o seu `/login` retornar um JSON que tem pelo menos o token de acesso do usuário caso ele tenha logado com sucesso

2019-05-09 12:11 UTC, alanraso commented on src/telalogin/login.ts
> +export function performLogin(req, res){
Como essa função recebe o `req` e o `res`, ela deveria ser responsável por retornar a resposta que o seu servidor dará para o client. E essa resposta precisa ter pelo menos o token de acesso dele, certo?

2019-05-10 19:22 UTC, alanraso approved these changes

2019-05-12 17:27 UTC, merged